### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by ntallapa12** [SohoHouse/nuxt-oauth#32]
I am getting the below error when trying to integrate next-oauth into my nuxt project, Below is the stack trace

(node:86432) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'match' of undefined
    at normalize (/Users/ntalla/Acxiom/git_repo/personal/factly/dega-web/node_modules/url-join/lib/url-join.js:11:21)
    at /Users/ntalla/Acxiom/git_repo/personal/factly/dega-web/node_modules/url-join/lib/url-join.js:70:12
    at Handler.createAuth (/Users/ntalla/Acxiom/git_repo/personal/factly/dega-web/node_modules/nuxt-oauth/lib/handler.js:33:23)
    at Handler.init (/Users/ntalla/Acxiom/git_repo/personal/factly/dega-web/node_modules/nuxt-oauth/lib/handler.js:16:20)
    at new Handler (/Users/ntalla/Acxiom/git_repo/personal/factly/dega-web/node_modules/nuxt-oauth/lib/handler.js:8:8)
    at /Users/ntalla/Acxiom/git_repo/personal/factly/dega-web/node_modules/nuxt-oauth/lib/server-middleware.js:17:19
    at <anonymous>

Any help is highly appreciated

**Comment by cedricium** [comment]
+1, seeing this as well and have no idea what the issue is. I followed the setup outlined in the README word-by-word.

**Comment by samtgarson** [comment]
I think @cedricium's solution is an acceptable one. 

If you're building an SPA remember not to build your client secret into the client side bundle.
